# Generated by Django 3.2.3 on 2021-10-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0015_pcash_pcredit_preceipt_psales_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRSales_Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.TextField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('internal_ref_no', models.TextField(max_length=100)),
                ('user_id', models.TextField(max_length=100)),
                ('due_on', models.TextField(max_length=100)),
                ('credit_limit_amt', models.TextField(max_length=100)),
                ('supp_id', models.TextField(max_length=100)),
                ('supp_name', models.TextField(max_length=100)),
                ('item_id1', models.TextField(max_length=100)),
                ('item_id2', models.TextField(max_length=100)),
                ('item_details1', models.TextField(max_length=100)),
                ('item_details2', models.TextField(max_length=100)),
                ('price1_1', models.TextField(max_length=100)),
                ('price1_2', models.TextField(max_length=100)),
                ('price2_1', models.TextField(max_length=100)),
                ('price2_2', models.TextField(max_length=100)),
                ('quantity1', models.TextField(max_length=100)),
                ('quantity2', models.TextField(max_length=100)),
                ('quantity3', models.TextField(max_length=100)),
                ('quantity4', models.TextField(max_length=100)),
                ('amount1', models.TextField(max_length=100)),
                ('amount2', models.TextField(max_length=100)),
                ('sales_ex1', models.TextField(max_length=100)),
                ('sales_ex2', models.TextField(max_length=100)),
                ('job1', models.TextField(max_length=100)),
                ('job2', models.TextField(max_length=100)),
                ('labour_charge', models.TextField(max_length=100)),
                ('other_charge', models.TextField(max_length=100)),
                ('total1', models.TextField(max_length=100)),
                ('total2', models.TextField(max_length=100)),
                ('total3', models.TextField(max_length=100)),
                ('total4', models.TextField(max_length=100)),
                ('total5', models.TextField(max_length=100)),
                ('total6', models.TextField(max_length=100)),
                ('discount', models.TextField(max_length=100)),
                ('tax', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='PSales_Return',
        ),
    ]
