# Generated by Django 3.2.3 on 2021-10-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0018_ledger_journal_ledger_masterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=100)),
                ('item_id', models.TextField(max_length=100)),
                ('item_name', models.TextField(max_length=100)),
                ('period', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='job_Masterdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=100)),
                ('reportdate', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='job_Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=100)),
                ('job', models.TextField(max_length=100)),
                ('job_id', models.TextField(max_length=100)),
                ('period', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=100)),
                ('reportdate', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=100)),
                ('reportdate', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Masterdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=100)),
                ('reportdate', models.TextField(max_length=100)),
            ],
        ),
    ]
