# Generated by Django 3.2.7 on 2021-10-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0019_item_statement_job_masterdata_job_statement_stock_adjustment_stock_balance_stock_masterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.TextField(max_length=100)),
                ('invoice_no', models.TextField(max_length=100)),
                ('customer_id', models.TextField(max_length=100)),
                ('customer_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Invoice_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=100)),
                ('report_date', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Masterdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=100)),
                ('report_date', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Outstand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=100)),
                ('report_date', models.TextField(max_length=100)),
                ('customer_name', models.TextField(max_length=100)),
                ('customer_id', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.TextField(max_length=100)),
                ('report_date', models.TextField(max_length=100)),
                ('customer_name', models.TextField(max_length=100)),
                ('receipt_no', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=100)),
                ('report_period', models.TextField(max_length=100)),
                ('customer_name', models.TextField(max_length=100)),
                ('customer_id', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='payment_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_name', models.TextField(max_length=100)),
                ('Supplier_id', models.TextField(max_length=100)),
                ('report_date', models.TextField(max_length=100)),
                ('voucher_no', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.TextField(max_length=100)),
                ('invoice_no', models.TextField(max_length=100)),
                ('Supplier_name', models.TextField(max_length=100)),
                ('Supplier_id', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Invoice_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=100)),
                ('report_date', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Masterdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=100)),
                ('report_date', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Outstand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=100)),
                ('report_date', models.TextField(max_length=100)),
                ('Supplier_name', models.TextField(max_length=100)),
                ('Supplier_id', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_name', models.TextField(max_length=100)),
                ('Supplier_id', models.TextField(max_length=100)),
                ('date', models.TextField(max_length=100)),
                ('report_period', models.TextField(max_length=100)),
            ],
        ),
    ]
