# Generated by Django 3.2.7 on 2021-10-26 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0020_customer_invoice_customer_invoice_receipt_customer_masterdata_customer_outstand_customer_receipt_cus'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_masterdata',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
