# Generated by Django 3.2.7 on 2021-10-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0022_rename_date_created_supplier_masterdata_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_masterdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
