# Generated by Django 3.2.7 on 2021-10-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0023_supplier_masterdata_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_masterdata',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
