# Generated by Django 3.2.7 on 2021-10-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0028_auto_20211026_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_masterdata',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
