# Generated by Django 3.2.7 on 2021-10-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0029_alter_supplier_masterdata_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_masterdata',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
