# Generated by Django 3.2.7 on 2021-10-27 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0030_alter_supplier_masterdata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
