# Generated by Django 3.2.7 on 2021-10-28 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0032_alter_customer_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
